name: nix-build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      # - name: Enable Nix cache
      #   uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build flake
        run: |
          nix build .#default --show-trace

      - name: Show logs
        if: failure()
        run: |
          drv=$(ls /nix/store/*simple-dftd3-*.drv | head -n1)
          echo "-- log for s-dftd3 $drv -------------------------"
          nix log "$drv"
          drv2=$(ls /nix/store/*tblite-*.drv | head -n1)
          echo "-- log for tblite $drv2 -------------------------------"
          nix log "$drv2"
          echo "=== file info ==="
          file /nix/store/*simple-dftd3*/include/s-dftd3/gcc-14.3.0/dftd3.mod || true
          echo "=== size ==="
          ls -lh /nix/store/*simple-dftd3*/include/s-dftd3/gcc-14.3.0/dftd3.mod || true
          echo "=== hexdump ==="
          head -c 64 /nix/store/*simple-dftd3*/include/s-dftd3/gcc-14.3.0/dftd3.mod | hexdump -C || true

      - name: Run binary
        run: |
          ./result/bin/crest --help || true
